import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import { auth0 } from '../../lib/auth0';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth0.getSession();
  const user = session?.user;

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <div className="app-container">
          <Providers user={user}>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
