"""create puzzle solutions

Revision ID: dbce0c210ada
Revises: 263776e29734
Create Date: 2026-02-05 14:12:57.408012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbce0c210ada'
down_revision: Union[str, Sequence[str], None] = '263776e29734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle_solutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('moves', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('final_fen', sa.Text(), nullable=True),
    sa.Column('raw_engine_out', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('solve_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['puzzle_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puzzle_solutions')
    # ### end Alembic commands ###
